all: bspm_P8_15_2e-00A0.dtbo bspm_P8_16_2e-00A0.dtbo bspm_P8_20_2e-00A0.dtbo bspm_P8_21_2e-00A0.dtbo bspm_P8_27_2e-00A0.dtbo bspm_P8_28_2e-00A0.dtbo bspm_P8_29_2e-00A0.dtbo bspm_P8_39_2e-00A0.dtbo bspm_P8_40_2e-00A0.dtbo bspm_P8_41_2e-00A0.dtbo bspm_P8_42_2e-00A0.dtbo bspm_P8_43_2e-00A0.dtbo bspm_P8_44_2e-00A0.dtbo bspm_P8_45_2e-00A0.dtbo bspm_P8_46_2e-00A0.dtbo
bspm_P8_15_2e-00A0.dtbo:
	dtc -O dtb -o /lib/firmware/bspm_P8_15_2e-00A0.dtbo -b 0 -@ bspm_P8_15_2e-00A0.dts
	
bspm_P8_16_2e-00A0.dtbo:
	dtc -O dtb -o /lib/firmware/bspm_P8_16_2e-00A0.dtbo -b 0 -@ bspm_P8_16_2e-00A0.dts
	
bspm_P8_20_2e-00A0.dtbo:
	dtc -O dtb -o /lib/firmware/bspm_P8_20_2e-00A0.dtbo -b 0 -@ bspm_P8_20_2e-00A0.dts
	
bspm_P8_21_2e-00A0.dtbo:
	dtc -O dtb -o /lib/firmware/bspm_P8_21_2e-00A0.dtbo -b 0 -@ bspm_P8_21_2e-00A0.dts
	
bspm_P8_27_2e-00A0.dtbo:
	dtc -O dtb -o /lib/firmware/bspm_P8_27_2e-00A0.dtbo -b 0 -@ bspm_P8_27_2e-00A0.dts
	
bspm_P8_28_2e-00A0.dtbo:
	dtc -O dtb -o /lib/firmware/bspm_P8_28_2e-00A0.dtbo -b 0 -@ bspm_P8_28_2e-00A0.dts
	
bspm_P8_29_2e-00A0.dtbo:
	dtc -O dtb -o /lib/firmware/bspm_P8_29_2e-00A0.dtbo -b 0 -@ bspm_P8_29_2e-00A0.dts
	
bspm_P8_39_2e-00A0.dtbo:
	dtc -O dtb -o /lib/firmware/bspm_P8_39_2e-00A0.dtbo -b 0 -@ bspm_P8_39_2e-00A0.dts
	
bspm_P8_40_2e-00A0.dtbo:
	dtc -O dtb -o /lib/firmware/bspm_P8_40_2e-00A0.dtbo -b 0 -@ bspm_P8_40_2e-00A0.dts
	
bspm_P8_41_2e-00A0.dtbo:
	dtc -O dtb -o /lib/firmware/bspm_P8_41_2e-00A0.dtbo -b 0 -@ bspm_P8_41_2e-00A0.dts
	
bspm_P8_42_2e-00A0.dtbo:
	dtc -O dtb -o /lib/firmware/bspm_P8_42_2e-00A0.dtbo -b 0 -@ bspm_P8_42_2e-00A0.dts
	
bspm_P8_43_2e-00A0.dtbo:
	dtc -O dtb -o /lib/firmware/bspm_P8_43_2e-00A0.dtbo -b 0 -@ bspm_P8_43_2e-00A0.dts
	
bspm_P8_44_2e-00A0.dtbo:
	dtc -O dtb -o /lib/firmware/bspm_P8_44_2e-00A0.dtbo -b 0 -@ bspm_P8_44_2e-00A0.dts
	
bspm_P8_45_2e-00A0.dtbo:
	dtc -O dtb -o /lib/firmware/bspm_P8_45_2e-00A0.dtbo -b 0 -@ bspm_P8_45_2e-00A0.dts
	
bspm_P8_46_2e-00A0.dtbo:
	dtc -O dtb -o /lib/firmware/bspm_P8_46_2e-00A0.dtbo -b 0 -@ bspm_P8_46_2e-00A0.dts
