all: bspm_P8_15_26-00A0.dtbo bspm_P8_16_26-00A0.dtbo bspm_P8_20_26-00A0.dtbo bspm_P8_21_26-00A0.dtbo bspm_P8_27_26-00A0.dtbo bspm_P8_28_26-00A0.dtbo bspm_P8_29_26-00A0.dtbo bspm_P8_39_26-00A0.dtbo bspm_P8_40_26-00A0.dtbo bspm_P8_41_26-00A0.dtbo bspm_P8_42_26-00A0.dtbo bspm_P8_43_26-00A0.dtbo bspm_P8_44_26-00A0.dtbo bspm_P8_45_26-00A0.dtbo bspm_P8_46_26-00A0.dtbo

bspm_P8_15_26-00A0.dtbo:
	dtc -O dtb -o /lib/firmware/bspm_P8_15_26-00A0.dtbo -b 0 -@ bspm_P8_15_26-00A0.dts
	
bspm_P8_16_26-00A0.dtbo:
	dtc -O dtb -o /lib/firmware/bspm_P8_16_26-00A0.dtbo -b 0 -@ bspm_P8_16_26-00A0.dts
	
bspm_P8_20_26-00A0.dtbo:
	dtc -O dtb -o /lib/firmware/bspm_P8_20_26-00A0.dtbo -b 0 -@ bspm_P8_20_26-00A0.dts
	
bspm_P8_21_26-00A0.dtbo:
	dtc -O dtb -o /lib/firmware/bspm_P8_21_26-00A0.dtbo -b 0 -@ bspm_P8_21_26-00A0.dts
	
bspm_P8_27_26-00A0.dtbo:
	dtc -O dtb -o /lib/firmware/bspm_P8_27_26-00A0.dtbo -b 0 -@ bspm_P8_27_26-00A0.dts
	
bspm_P8_28_26-00A0.dtbo:
	dtc -O dtb -o /lib/firmware/bspm_P8_28_26-00A0.dtbo -b 0 -@ bspm_P8_28_26-00A0.dts
	
bspm_P8_29_26-00A0.dtbo:
	dtc -O dtb -o /lib/firmware/bspm_P8_29_26-00A0.dtbo -b 0 -@ bspm_P8_29_26-00A0.dts
	
bspm_P8_39_26-00A0.dtbo:
	dtc -O dtb -o /lib/firmware/bspm_P8_39_26-00A0.dtbo -b 0 -@ bspm_P8_39_26-00A0.dts
	
bspm_P8_40_26-00A0.dtbo:
	dtc -O dtb -o /lib/firmware/bspm_P8_40_26-00A0.dtbo -b 0 -@ bspm_P8_40_26-00A0.dts
	
bspm_P8_41_26-00A0.dtbo:
	dtc -O dtb -o /lib/firmware/bspm_P8_41_26-00A0.dtbo -b 0 -@ bspm_P8_41_26-00A0.dts
	
bspm_P8_42_26-00A0.dtbo:
	dtc -O dtb -o /lib/firmware/bspm_P8_42_26-00A0.dtbo -b 0 -@ bspm_P8_42_26-00A0.dts
	
bspm_P8_43_26-00A0.dtbo:
	dtc -O dtb -o /lib/firmware/bspm_P8_43_26-00A0.dtbo -b 0 -@ bspm_P8_43_26-00A0.dts
	
bspm_P8_44_26-00A0.dtbo:
	dtc -O dtb -o /lib/firmware/bspm_P8_44_26-00A0.dtbo -b 0 -@ bspm_P8_44_26-00A0.dts
	
bspm_P8_45_26-00A0.dtbo:
	dtc -O dtb -o /lib/firmware/bspm_P8_45_26-00A0.dtbo -b 0 -@ bspm_P8_45_26-00A0.dts
	
bspm_P8_46_26-00A0.dtbo:
	dtc -O dtb -o /lib/firmware/bspm_P8_46_26-00A0.dtbo -b 0 -@ bspm_P8_46_26-00A0.dts