all: bspm_P9_28_5-00A0.dtbo bspm_P9_29_5-00A0.dtbo bspm_P9_30_5-00A0.dtbo bspm_P9_31_5-00A0.dtbo
	
bspm_P9_28_5-00A0.dtbo:
	dtc -O dtb -o /lib/firmware/bspm_P9_28_5-00A0.dtbo -b 0 -@ bspm_P9_28_5-00A0.dts
	
bspm_P9_29_5-00A0.dtbo:
	dtc -O dtb -o /lib/firmware/bspm_P9_29_5-00A0.dtbo -b 0 -@ bspm_P9_29_5-00A0.dts
	
bspm_P9_30_5-00A0.dtbo:
	dtc -O dtb -o /lib/firmware/bspm_P9_30_5-00A0.dtbo -b 0 -@ bspm_P9_30_5-00A0.dts
	
bspm_P9_31_5-00A0.dtbo:
	dtc -O dtb -o /lib/firmware/bspm_P9_31_5-00A0.dtbo -b 0 -@ bspm_P9_31_5-00A0.dts
