all: bspm_P9_28_d-00A0.dtbo bspm_P9_29_d-00A0.dtbo bspm_P9_30_d-00A0.dtbo bspm_P9_31_d-00A0.dtbo
	
bspm_P9_28_d-00A0.dtbo:
	dtc -O dtb -o /lib/firmware/bspm_P9_28_d-00A0.dtbo -b 0 -@ bspm_P9_28_d-00A0.dts
	
bspm_P9_29_d-00A0.dtbo:
	dtc -O dtb -o /lib/firmware/bspm_P9_29_d-00A0.dtbo -b 0 -@ bspm_P9_29_d-00A0.dts
	
bspm_P9_30_d-00A0.dtbo:
	dtc -O dtb -o /lib/firmware/bspm_P9_30_d-00A0.dtbo -b 0 -@ bspm_P9_30_d-00A0.dts
	
bspm_P9_31_d-00A0.dtbo:
	dtc -O dtb -o /lib/firmware/bspm_P9_31_d-00A0.dtbo -b 0 -@ bspm_P9_31_d-00A0.dts
